### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Anas-Abdelhadi** [rsuite/responsive-nav#5]
When trying to run build, or during development, in a typescript project I receive the following errors:

ERROR in D:/playground/Project/app/node_modules/@rsuite/responsive-nav/index.d.ts(26,1):
**TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.**
ERROR in D:/playground/Project/app/node_modules/@rsuite/responsive-nav/index.d.ts(26,32):
**TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.**

**Comment by simonguo** [comment]
Which version are you using?

**Comment by Anas-Abdelhadi** [comment]
TS: 3.5.1
@rsuite/responsive-nav: **0.0.6**
rsuite : **4.2.0**
react : **16.8.6**

**Comment by simonguo** [comment]
```
npm install @rsuite/responsive-nav@0.0.7
```

**Comment by Anas-Abdelhadi** [comment]
Thanks a lot. It's resolved now.
